os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="libtiff/4.0.6"
    - CONAN_USERNAME="bilke"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
    - os: osx
      osx_image: xcode8.1
      language: generic
      env:
    - os: osx
      osx_image: xcode8
      language: generic
      env:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
    - os: osx
      osx_image: xcode7.1
      language: generic
      env:
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
    - os: osx
      osx_image: xcode6.2
      language: generic
      env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
